Squashed commit from kernels branch of the following:
commit 80256e64e156824dd3558685aafb983abd73f8ec
Author: Akhil Raj Azhikodan <aazhiko@amazon.com>
Date:   Tue Oct 22 01:52:03 2024 +0000

    feat: Add speculative TP degree and KV cache tiling

    "cr: https://code.amazon.com/reviews/CR-155479432"

commit d8a5093af5dc11797a0e684e5c6b7da21662a1fe
Author: Piyush Dugar <piydugar@amazon.com>
Date:   Wed Oct 16 19:55:36 2024 -0700

    feat: cleanup fp8 quantized kernel for MLP

    "cr: https://code.amazon.com/reviews/CR-154787811"

commit db1f1991109abad4cf1c82fb3d9ecda87c0cb314
Author: Joey Zheng <yunhaz@amazon.com>
Date:   Fri Oct 18 20:30:20 2024 +0000

    Move rmsnorm out of MLP

    "cr: https://code.amazon.com/reviews/CR-155003413"

commit 3786353eb5564e7ec446a074b394010cab33119f
Author: Joey Zheng <yunhaz@amazon.com>
Date:   Thu Oct 17 23:49:59 2024 +0000

    Move input RMSNorm outside GQA

    "cr: https://code.amazon.com/reviews/CR-154937371"

commit 5bbdea4625a60c3d498db487f8fe24911f51feb5
Author: Joey Zheng <yunhaz@amazon.com>
Date:   Thu Oct 17 06:48:02 2024 +0000

    Clean up MLP kernel

    "cr: https://code.amazon.com/reviews/CR-154815275"

commit 8935703495ca851e6ba6402c4f822d7677eb138d
Author: Joey Zheng <yunhaz@amazon.com>
Date:   Wed Oct 16 23:49:20 2024 +0000

    Enable flash attn kernel by default for long context

commit a8e0cfd250c8cac33470229080dd2ba6d41a273d
Author: Beni Hegedus <bhegedus@amazon.com>
Date:   Thu Oct 17 18:00:48 2024 +0000

    Add fp8 MLP per-channel kernel support && weight sharding/loading support for fp8 per-channel kernels

    "cr: https://code.amazon.com/reviews/CR-154902950"

commit b6971509e3d03d66d78a3a82e3ce17e38b77944d
Author: Akhil Raj Azhikodan <aazhiko@amazon.com>
Date:   Sat Oct 12 23:19:34 2024 +0000

    Add kernel flags and correct compiler flags

commit d8914d7fadf12119964baa7dec96b1af31020900
Author: Amulya Ballakur <amulyaab@amazon.com>
Date:   Wed Oct 9 21:47:35 2024 +0000

    [feat] Fused speculative decoding

    "SIM: https://i.amazon.com/NAPP-5346"
    "cr: https://code.amazon.com/reviews/CR-153468001"

commit 518c498fd863bc2b8fa3b16fc8f8c01954541c75
Author: Andrew Canis <acanis@amazon.com>
Date:   Fri Oct 11 18:52:03 2024 +0000

    Pass store_add to the FP8 quantized MLP kernel for fused residual

    "cr: https://code.amazon.com/reviews/CR-149997841"

commit 31c9d8293f9b284c9c897431dd5b3976e18d11d5
Author: Andrew Canis <acanis@amazon.com>
Date:   Fri Oct 11 18:08:38 2024 +0000

    Switch to Neuron logger

    "cr: https://code.amazon.com/reviews/CR-149997841"

commit 4a6dd3a86c35c463f7eb09b1f52f0eb0480dc5e3
Author: Beni Hegedus <bhegedus@amazon.com>
Date:   Thu Oct 10 17:27:47 2024 +0000

    Add fp8 MLP kernels for llama

    Cherry pick from @bhegedus CR-153663538

    "cr: https://code.amazon.com/reviews/CR-149997841"

commit 7fac4357721b58d90ef616ea7c83990f20af931a
Author: Andrew Canis <acanis@amazon.com>
Date:   Wed Oct 9 19:35:23 2024 +0000

    Change Neuron Config parameter from sequence_parallel_norm -> sequence_parallel_enabled

    We should use the same config variable name as the NeuronConfig
    paramemter to allow us to correctly save/load from neuron_config.json file

    Background:
    I added better error checking of keyword args to config.py NeuronConfig init:
    	assert not kwargs, f"NeuronConfig init: Unexpected keyword arguments: {kwargs}"

    Then I just saw this when running a pre-traced model:
    	AssertionError: NeuronConfig init: Unexpected keyword arguments: {'sequence_parallel_enabled': False}

    In config.py I notice there is a mismatch between the config variable for seq parallel:
    	self.sequence_parallel_enabled = kwargs.pop("sequence_parallel_norm", False)

    In the traced_models/llama3-405b-4layers-lnc2/neuron_config.json I see
    	sequence_parallel_enabled": false, (edited)

    "cr: https://code.amazon.com/reviews/CR-149997841"

commit 367514147edf6831c04499fac3ac29247874de90
Author: Andrew Canis <acanis@amazon.com>
Date:   Fri Sep 27 19:05:07 2024 +0000

    Simplified the QKV weight transpose, neuron config plumbing, refactoring

     - The TKG QKV kernel can support LNC=2. Therefore we only need one copy
       of the QKV weights that is transposed when using the QKV kernel that
      can be shared with both CTE and TKG QKV kernels.

    - Add neuron config parameters for compiler settings and skippping
      weight sharding
      Now parameters for neuronx-cc compiler args:
         cc_pipeline_tiling_factor
         target
      Also "skip_weight_sharding" to save time if the weights are
      already sharded

     - Added warning for invalid neuron config parameters.

    - Print out the compiler log into the compiler artifacts directory

    - Fixed the logic for only fusing the residual when the MLP kernel is
      enabled.

    - Changed all print debug statements to use logging.debug

    - In the QKV forward pass - RMSNorm should be optionally applied
        In mixtral model, we perform RMSNorm before calling QKV/attention.

    - Refactor QKV kernel call into simpler function

    - Move kernel weight transpose out of NxD layer. Thanks @bhegedus for
      the change

    - Add the apply_transpose attribute to transpose the sharded weight
      checkpoints. Thanks @piydugar for suggestion.

    - Do not pass grid to attention kernel when LNC=1 since this is not
      supported by the attention kernel

    "cr: https://code.amazon.com/reviews/CR-149997841"

commit ddf204e9c9333468d512205645e0ecd37cf4810e
Author: Haoda Li <lihaoda@amazon.com>
Date:   Fri Sep 27 20:09:45 2024 +0000

    Integrate TKG MLP and TKG QKV kernels

    Move weight transpose from MLP kernel forward to init to improve
    performance

    "cr: https://code.amazon.com/reviews/CR-149997841"

commit a2095f3e01595d9b1af203b29e51cd7a2ca4f416
Author: Andrew Uderian <auderian@amazon.com>
Date:   Fri Sep 20 19:48:05 2024 +0000

    Initial integration of QKV, ATTN, MLP kernels

    Add SP norm and MLP residual add fusion
    Also, disable kernels if in tokengen

    "cr: https://code.amazon.com/reviews/CR-149997841"